name: Publish to Buf Schema Registry
on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    if: ${{ !github.event.release.prerelease }}
    name: Publish to Buf Schema Registry
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true