name: Rust CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  rust:
    name: Generate crate and lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v7

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          version: 1.72.0
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Generate the bolt-proto crate
        run: just rust

      - name: Clippy
        working-directory: rust
        run: cargo clippy --all-targets -- -D warnings
